//------------------------------------------------------------------------------
// Source code generated by wxDesigner from file: SimpleEdit.wdr
// Do not modify this file, all changes will be lost!
//------------------------------------------------------------------------------

#ifdef __GNUG__
    #pragma implementation "SimpleEdit_wdr.h"
#endif

// For compilers that support precompilation
#include "wx/wxprec.h"

#ifdef __BORLANDC__
    #pragma hdrstop
#endif

// Include private header
#include "SimpleEdit_wdr.h"


// Implement window functions

wxSizer *ItemEdit( wxWindow *parent, bool call_fit, bool set_sizer )
{
    wxBoxSizer *item0 = new wxBoxSizer( wxVERTICAL );

    wxStaticText *item1 = new wxStaticText( parent, ID_TEXT, wxT("Item Editor"), wxDefaultPosition, wxDefaultSize, wxALIGN_CENTRE );
    item1->SetFont( wxFont( 18, wxSWISS, wxNORMAL, wxNORMAL ) );
#if defined(__WXMSW__) && !(wxCHECK_VERSION(2,3,0))
    item1->SetSize( item1->GetBestSize() );
#endif
    item0->Add( item1, 0, wxALIGN_CENTER|wxALL, 5 );

    wxGridSizer *item2 = new wxGridSizer( 5, 0, 0 );

    wxStaticText *item3 = new wxStaticText( parent, ID_TEXT, wxT("Item ID:"), wxDefaultPosition, wxDefaultSize, 0 );
    item2->Add( item3, 0, wxALIGN_CENTER|wxALL, 5 );

    wxSpinCtrl *item4 = new wxSpinCtrl( parent, ID_ITEMID, wxT("0"), wxDefaultPosition, wxSize(100,-1), 0, 0, 65536, 0 );
    item2->Add( item4, 0, wxALIGN_CENTER|wxALL, 5 );

    wxButton *item5 = new wxButton( parent, ID_ITEMNEW, wxT("New"), wxDefaultPosition, wxDefaultSize, 0 );
    item2->Add( item5, 0, wxALIGN_CENTER|wxALL, 5 );

    wxButton *item6 = new wxButton( parent, ID_ITEMSAVE, wxT("Save Item"), wxDefaultPosition, wxDefaultSize, 0 );
    item2->Add( item6, 0, wxALIGN_CENTER|wxALL, 5 );

    wxButton *item7 = new wxButton( parent, ID_ITEMDELETE, wxT("Delete Item"), wxDefaultPosition, wxDefaultSize, 0 );
    item2->Add( item7, 0, wxALIGN_CENTER|wxALL, 5 );

    item0->Add( item2, 0, wxALIGN_CENTER|wxALL, 5 );

    wxBoxSizer *item8 = new wxBoxSizer( wxHORIZONTAL );

    wxStaticBox *item10 = new wxStaticBox( parent, -1, wxT("Item Attributes") );
    wxStaticBoxSizer *item9 = new wxStaticBoxSizer( item10, wxVERTICAL );

    wxFlexGridSizer *item11 = new wxFlexGridSizer( 2, 0, 0 );

    wxStaticText *item12 = new wxStaticText( parent, ID_TEXT, wxT("Name"), wxDefaultPosition, wxDefaultSize, 0 );
    item11->Add( item12, 0, wxALIGN_RIGHT|wxALL, 5 );

    wxTextCtrl *item13 = new wxTextCtrl( parent, ID_ITEMNAME, wxT(""), wxDefaultPosition, wxSize(200,-1), 0 );
    item11->Add( item13, 0, wxALIGN_CENTER, 5 );

    wxStaticText *item14 = new wxStaticText( parent, ID_TEXT, wxT("Type"), wxDefaultPosition, wxDefaultSize, 0 );
    item11->Add( item14, 0, wxALIGN_RIGHT|wxALIGN_CENTER_VERTICAL|wxALL, 5 );

    wxString strs15[] = 
    {
        wxT("WEAPON"), 
        wxT("ARMOR"), 
        wxT("HEALING")
    };
    wxComboBox *item15 = new wxComboBox( parent, ID_ITEMTYPE, wxT(""), wxDefaultPosition, wxSize(200,-1), 3, strs15, wxCB_DROPDOWN );
    item11->Add( item15, 0, wxALIGN_CENTER, 5 );

    wxStaticText *item16 = new wxStaticText( parent, ID_TEXT, wxT("Min"), wxDefaultPosition, wxDefaultSize, 0 );
    item11->Add( item16, 0, wxALIGN_RIGHT|wxALIGN_CENTER_VERTICAL|wxALL, 5 );

    wxTextCtrl *item17 = new wxTextCtrl( parent, ID_ITEMMIN, wxT(""), wxDefaultPosition, wxSize(200,-1), 0 );
    item11->Add( item17, 0, wxALIGN_CENTER, 5 );

    wxStaticText *item18 = new wxStaticText( parent, ID_TEXT, wxT("Max"), wxDefaultPosition, wxDefaultSize, 0 );
    item11->Add( item18, 0, wxALIGN_RIGHT|wxALIGN_CENTER_VERTICAL|wxALL, 5 );

    wxTextCtrl *item19 = new wxTextCtrl( parent, ID_ITEMMAX, wxT(""), wxDefaultPosition, wxSize(200,-1), 0 );
    item11->Add( item19, 0, wxALIGN_CENTER, 5 );

    wxStaticText *item20 = new wxStaticText( parent, ID_TEXT, wxT("Speed"), wxDefaultPosition, wxDefaultSize, 0 );
    item11->Add( item20, 0, wxALIGN_RIGHT|wxALIGN_CENTER_VERTICAL|wxALL, 5 );

    wxTextCtrl *item21 = new wxTextCtrl( parent, ID_ITEMSPEED, wxT(""), wxDefaultPosition, wxSize(200,-1), 0 );
    item11->Add( item21, 0, wxALIGN_CENTER, 5 );

    wxStaticText *item22 = new wxStaticText( parent, ID_TEXT, wxT("Price"), wxDefaultPosition, wxDefaultSize, 0 );
    item11->Add( item22, 0, wxALIGN_RIGHT|wxALIGN_CENTER_VERTICAL|wxALL, 5 );

    wxTextCtrl *item23 = new wxTextCtrl( parent, ID_ITEMPRICE, wxT(""), wxDefaultPosition, wxSize(200,-1), 0 );
    item11->Add( item23, 0, wxALIGN_CENTER|wxALL, 0 );

    item9->Add( item11, 0, wxADJUST_MINSIZE|wxALIGN_CENTER_VERTICAL|wxSHAPED, 15 );

    item8->Add( item9, 0, wxALIGN_CENTER_HORIZONTAL|wxALL, 5 );

    wxStaticBox *item25 = new wxStaticBox( parent, -1, wxT("Player Modifiers") );
    wxStaticBoxSizer *item24 = new wxStaticBoxSizer( item25, wxVERTICAL );

    wxFlexGridSizer *item26 = new wxFlexGridSizer( 2, 0, 0 );
    item26->AddGrowableCol( 0 );

    wxStaticText *item27 = new wxStaticText( parent, ID_TEXT, wxT("Strength"), wxDefaultPosition, wxDefaultSize, 0 );
    item26->Add( item27, 0, wxALIGN_RIGHT|wxALIGN_CENTER_VERTICAL|wxALL, 5 );

    wxTextCtrl *item28 = new wxTextCtrl( parent, ID_ITEMSTRENGTH, wxT(""), wxDefaultPosition, wxSize(160,-1), 0 );
    item26->Add( item28, 0, wxALIGN_CENTER|wxALL, 0 );

    wxStaticText *item29 = new wxStaticText( parent, ID_TEXT, wxT("Health"), wxDefaultPosition, wxDefaultSize, 0 );
    item26->Add( item29, 0, wxALIGN_RIGHT|wxALIGN_CENTER_VERTICAL|wxALL, 5 );

    wxTextCtrl *item30 = new wxTextCtrl( parent, ID_ITEMHEALTH, wxT(""), wxDefaultPosition, wxSize(160,-1), 0 );
    item26->Add( item30, 0, wxALIGN_CENTER|wxALL, 0 );

    wxStaticText *item31 = new wxStaticText( parent, ID_TEXT, wxT("Agility"), wxDefaultPosition, wxDefaultSize, 0 );
    item26->Add( item31, 0, wxALIGN_RIGHT|wxALIGN_CENTER_VERTICAL|wxALL, 5 );

    wxTextCtrl *item32 = new wxTextCtrl( parent, ID_ITEMAGILITY, wxT(""), wxDefaultPosition, wxSize(160,-1), 0 );
    item26->Add( item32, 0, wxALIGN_CENTER|wxALL, 0 );

    wxStaticText *item33 = new wxStaticText( parent, ID_TEXT, wxT("MaxHP"), wxDefaultPosition, wxDefaultSize, 0 );
    item26->Add( item33, 0, wxALIGN_RIGHT|wxALIGN_CENTER_VERTICAL|wxALL, 5 );

    wxTextCtrl *item34 = new wxTextCtrl( parent, ID_ITEMMAXHP, wxT(""), wxDefaultPosition, wxSize(160,-1), 0 );
    item26->Add( item34, 0, wxALIGN_CENTER|wxALL, 0 );

    wxStaticText *item35 = new wxStaticText( parent, ID_TEXT, wxT("Accuracy"), wxDefaultPosition, wxDefaultSize, 0 );
    item26->Add( item35, 0, wxALIGN_RIGHT|wxALIGN_CENTER_VERTICAL|wxALL, 5 );

    wxTextCtrl *item36 = new wxTextCtrl( parent, ID_ITEMACCURACY, wxT(""), wxDefaultPosition, wxSize(160,-1), 0 );
    item26->Add( item36, 0, wxALIGN_CENTER|wxALL, 0 );

    wxStaticText *item37 = new wxStaticText( parent, ID_TEXT, wxT("Dodging"), wxDefaultPosition, wxDefaultSize, 0 );
    item26->Add( item37, 0, wxALIGN_RIGHT|wxALIGN_CENTER_VERTICAL|wxALL, 5 );

    wxTextCtrl *item38 = new wxTextCtrl( parent, ID_ITEMDODGING, wxT(""), wxDefaultPosition, wxSize(160,-1), 0 );
    item26->Add( item38, 0, wxALIGN_CENTER|wxALL, 0 );

    wxStaticText *item39 = new wxStaticText( parent, ID_TEXT, wxT("Strike Damage"), wxDefaultPosition, wxDefaultSize, 0 );
    item26->Add( item39, 0, wxALIGN_RIGHT|wxALIGN_CENTER_VERTICAL|wxALL, 5 );

    wxTextCtrl *item40 = new wxTextCtrl( parent, ID_ITEMSTRIKEDAMAGE, wxT(""), wxDefaultPosition, wxSize(160,-1), 0 );
    item26->Add( item40, 0, wxALIGN_CENTER|wxALL, 0 );

    wxStaticText *item41 = new wxStaticText( parent, ID_TEXT, wxT("Damage Absorption"), wxDefaultPosition, wxDefaultSize, 0 );
    item26->Add( item41, 0, wxALIGN_RIGHT|wxALIGN_CENTER_VERTICAL|wxALL, 5 );

    wxTextCtrl *item42 = new wxTextCtrl( parent, ID_ITEMDAMAGEABSORB, wxT(""), wxDefaultPosition, wxSize(160,-1), 0 );
    item26->Add( item42, 0, wxALIGN_CENTER|wxALL, 0 );

    wxStaticText *item43 = new wxStaticText( parent, ID_TEXT, wxT("HP Regen"), wxDefaultPosition, wxDefaultSize, 0 );
    item26->Add( item43, 0, wxALIGN_RIGHT|wxALIGN_CENTER_VERTICAL|wxALL, 5 );

    wxTextCtrl *item44 = new wxTextCtrl( parent, ID_ITEMHPREGEN, wxT(""), wxDefaultPosition, wxSize(160,-1), 0 );
    item26->Add( item44, 0, wxALIGN_CENTER|wxALL, 0 );

    item24->Add( item26, 0, wxALIGN_CENTER|wxALL, 5 );

    item8->Add( item24, 0, wxALIGN_CENTER_HORIZONTAL|wxALL, 5 );

    item0->Add( item8, 0, wxALIGN_CENTER|wxALL, 5 );

    if (set_sizer)
    {
        parent->SetAutoLayout( TRUE );
        parent->SetSizer( item0 );
        if (call_fit)
        {
            item0->Fit( parent );
            item0->SetSizeHints( parent );
        }
    }
    
    return item0;
}

wxSizer *PlayerEdit( wxWindow *parent, bool call_fit, bool set_sizer )
{
    wxBoxSizer *item0 = new wxBoxSizer( wxVERTICAL );

    wxStaticText *item1 = new wxStaticText( parent, ID_TEXT, wxT("Player Editor"), wxDefaultPosition, wxDefaultSize, 0 );
    item1->SetFont( wxFont( 18, wxSWISS, wxNORMAL, wxNORMAL ) );
#if defined(__WXMSW__) && !(wxCHECK_VERSION(2,3,0))
    item1->SetSize( item1->GetBestSize() );
#endif
    item0->Add( item1, 0, wxALIGN_CENTER|wxALL, 5 );

    wxFlexGridSizer *item2 = new wxFlexGridSizer( 5, 0, 0 );

    wxStaticText *item3 = new wxStaticText( parent, ID_TEXT, wxT("Player ID"), wxDefaultPosition, wxDefaultSize, 0 );
    item2->Add( item3, 0, wxALIGN_CENTER|wxALL, 5 );

    wxSpinCtrl *item4 = new wxSpinCtrl( parent, ID_PLAYERID, wxT("0"), wxDefaultPosition, wxSize(100,-1), 0, 0, 1000000, 0 );
    item2->Add( item4, 0, wxALIGN_CENTER|wxALL, 5 );

    wxButton *item5 = new wxButton( parent, ID_PLAYERNEW, wxT("New"), wxDefaultPosition, wxDefaultSize, 0 );
    item2->Add( item5, 0, wxALIGN_CENTER|wxALL, 5 );

    wxButton *item6 = new wxButton( parent, ID_PLAYERSAVE, wxT("Save"), wxDefaultPosition, wxDefaultSize, 0 );
    item2->Add( item6, 0, wxALIGN_CENTER|wxALL, 5 );

    wxButton *item7 = new wxButton( parent, ID_PLAYERDELETE, wxT("Delete"), wxDefaultPosition, wxDefaultSize, 0 );
    item2->Add( item7, 0, wxALIGN_CENTER|wxALL, 5 );

    item0->Add( item2, 0, wxALIGN_CENTER|wxALL, 5 );

    wxBoxSizer *item8 = new wxBoxSizer( wxHORIZONTAL );

    wxStaticBox *item10 = new wxStaticBox( parent, -1, wxT("Player Stats") );
    wxStaticBoxSizer *item9 = new wxStaticBoxSizer( item10, wxVERTICAL );

    wxFlexGridSizer *item11 = new wxFlexGridSizer( 2, 0, 0 );

    wxStaticText *item12 = new wxStaticText( parent, ID_TEXT, wxT("Name"), wxDefaultPosition, wxDefaultSize, 0 );
    item11->Add( item12, 0, wxALIGN_RIGHT|wxALIGN_CENTER_VERTICAL|wxALL, 5 );

    wxTextCtrl *item13 = new wxTextCtrl( parent, ID_PLAYERNAME, wxT(""), wxDefaultPosition, wxSize(160,-1), 0 );
    item11->Add( item13, 0, wxALIGN_CENTER|wxALL, 5 );

    wxStaticText *item14 = new wxStaticText( parent, ID_TEXT, wxT("Password"), wxDefaultPosition, wxDefaultSize, 0 );
    item11->Add( item14, 0, wxALIGN_RIGHT|wxALIGN_CENTER_VERTICAL|wxALL, 5 );

    wxTextCtrl *item15 = new wxTextCtrl( parent, ID_PLAYERPASS, wxT(""), wxDefaultPosition, wxSize(160,-1), 0 );
    item11->Add( item15, 0, wxALIGN_CENTER|wxALL, 5 );

    wxStaticText *item16 = new wxStaticText( parent, ID_TEXT, wxT("Rank"), wxDefaultPosition, wxDefaultSize, 0 );
    item11->Add( item16, 0, wxALIGN_RIGHT|wxALIGN_CENTER_VERTICAL|wxALL, 5 );

    wxString strs17[] = 
    {
        wxT("REGULAR"), 
        wxT("GOD"), 
        wxT("ADMIN")
    };
    wxComboBox *item17 = new wxComboBox( parent, ID_PLAYERRANK, wxT(""), wxDefaultPosition, wxSize(160,-1), 3, strs17, wxCB_DROPDOWN );
    item11->Add( item17, 0, wxALIGN_CENTER|wxALL, 5 );

    wxStaticText *item18 = new wxStaticText( parent, ID_TEXT, wxT("Statpoints"), wxDefaultPosition, wxDefaultSize, 0 );
    item11->Add( item18, 0, wxALIGN_RIGHT|wxALIGN_CENTER_VERTICAL|wxALL, 5 );

    wxTextCtrl *item19 = new wxTextCtrl( parent, ID_PLAYERSTATPOINTS, wxT(""), wxDefaultPosition, wxSize(160,-1), 0 );
    item11->Add( item19, 0, wxALIGN_CENTER|wxALL, 5 );

    wxStaticText *item20 = new wxStaticText( parent, ID_TEXT, wxT("Experience"), wxDefaultPosition, wxDefaultSize, 0 );
    item11->Add( item20, 0, wxALIGN_RIGHT|wxALIGN_CENTER_VERTICAL|wxALL, 5 );

    wxTextCtrl *item21 = new wxTextCtrl( parent, ID_PLAYEREXPERIENCE, wxT(""), wxDefaultPosition, wxSize(160,-1), 0 );
    item11->Add( item21, 0, wxALIGN_CENTER|wxALL, 5 );

    wxStaticText *item22 = new wxStaticText( parent, ID_TEXT, wxT("Level"), wxDefaultPosition, wxDefaultSize, 0 );
    item11->Add( item22, 0, wxALIGN_RIGHT|wxALIGN_CENTER_VERTICAL|wxALL, 5 );

    wxTextCtrl *item23 = new wxTextCtrl( parent, ID_PLAYERLEVEL, wxT(""), wxDefaultPosition, wxSize(160,-1), 0 );
    item11->Add( item23, 0, wxALIGN_CENTER|wxALL, 5 );

    wxStaticText *item24 = new wxStaticText( parent, ID_TEXT, wxT("Room"), wxDefaultPosition, wxDefaultSize, 0 );
    item11->Add( item24, 0, wxALIGN_RIGHT|wxALIGN_CENTER_VERTICAL|wxALL, 5 );

    wxTextCtrl *item25 = new wxTextCtrl( parent, ID_PLAYERROOM, wxT(""), wxDefaultPosition, wxSize(160,-1), 0 );
    item11->Add( item25, 0, wxALIGN_CENTER|wxALL, 5 );

    wxStaticText *item26 = new wxStaticText( parent, ID_TEXT, wxT("Hitpoints"), wxDefaultPosition, wxDefaultSize, 0 );
    item11->Add( item26, 0, wxALIGN_RIGHT|wxALIGN_CENTER_VERTICAL|wxALL, 5 );

    wxTextCtrl *item27 = new wxTextCtrl( parent, ID_PLAYERHP, wxT(""), wxDefaultPosition, wxSize(160,-1), 0 );
    item11->Add( item27, 0, wxALIGN_CENTER|wxALL, 5 );

    wxStaticText *item28 = new wxStaticText( parent, ID_TEXT, wxT("Next Attack Time"), wxDefaultPosition, wxDefaultSize, 0 );
    item11->Add( item28, 0, wxALIGN_RIGHT|wxALIGN_CENTER_VERTICAL|wxALL, 5 );

    wxTextCtrl *item29 = new wxTextCtrl( parent, ID_PLAYERATTACKTIME, wxT(""), wxDefaultPosition, wxSize(160,-1), 0 );
    item11->Add( item29, 0, wxALIGN_CENTER|wxALL, 5 );

    item9->Add( item11, 0, wxALIGN_CENTER|wxALL, 5 );

    item8->Add( item9, 0, wxALIGN_CENTER_HORIZONTAL|wxALL, 5 );

    wxStaticBox *item31 = new wxStaticBox( parent, -1, wxT("Player Attributes") );
    wxStaticBoxSizer *item30 = new wxStaticBoxSizer( item31, wxVERTICAL );

    wxFlexGridSizer *item32 = new wxFlexGridSizer( 3, 0, 0 );

    item32->Add( 20, 20, 0, wxALIGN_CENTER|wxALL, 5 );

    wxStaticText *item33 = new wxStaticText( parent, ID_TEXT, wxT("Base"), wxDefaultPosition, wxDefaultSize, 0 );
    item33->SetFont( wxFont( 11, wxSWISS, wxNORMAL, wxBOLD ) );
#if defined(__WXMSW__) && !(wxCHECK_VERSION(2,3,0))
    item33->SetSize( item33->GetBestSize() );
#endif
    item32->Add( item33, 0, wxALIGN_CENTER|wxALL, 5 );

    wxStaticText *item34 = new wxStaticText( parent, ID_TEXT, wxT("Final"), wxDefaultPosition, wxDefaultSize, 0 );
    item34->SetFont( wxFont( 11, wxSWISS, wxNORMAL, wxBOLD ) );
#if defined(__WXMSW__) && !(wxCHECK_VERSION(2,3,0))
    item34->SetSize( item34->GetBestSize() );
#endif
    item32->Add( item34, 0, wxALIGN_CENTER|wxALL, 5 );

    wxStaticText *item35 = new wxStaticText( parent, ID_TEXT, wxT("Strength"), wxDefaultPosition, wxDefaultSize, 0 );
    item32->Add( item35, 0, wxALIGN_RIGHT|wxALIGN_CENTER_VERTICAL|wxALL, 5 );

    wxTextCtrl *item36 = new wxTextCtrl( parent, ID_PLAYERSTRENGTH, wxT(""), wxDefaultPosition, wxSize(80,-1), 0 );
    item32->Add( item36, 0, wxALIGN_CENTER|wxALL, 5 );

    wxTextCtrl *item37 = new wxTextCtrl( parent, ID_PLAYERSTRENGTHF, wxT(""), wxDefaultPosition, wxSize(80,-1), wxTE_READONLY );
    item32->Add( item37, 0, wxALIGN_CENTER|wxALL, 5 );

    wxStaticText *item38 = new wxStaticText( parent, ID_TEXT, wxT("Health"), wxDefaultPosition, wxDefaultSize, 0 );
    item32->Add( item38, 0, wxALIGN_RIGHT|wxALIGN_CENTER_VERTICAL|wxALL, 5 );

    wxTextCtrl *item39 = new wxTextCtrl( parent, ID_PLAYERHEALTH, wxT(""), wxDefaultPosition, wxSize(80,-1), 0 );
    item32->Add( item39, 0, wxALIGN_CENTER|wxALL, 5 );

    wxTextCtrl *item40 = new wxTextCtrl( parent, ID_PLAYERHEALTHF, wxT(""), wxDefaultPosition, wxSize(80,-1), wxTE_READONLY );
    item32->Add( item40, 0, wxALIGN_CENTER|wxALL, 5 );

    wxStaticText *item41 = new wxStaticText( parent, ID_TEXT, wxT("Agility"), wxDefaultPosition, wxDefaultSize, 0 );
    item32->Add( item41, 0, wxALIGN_RIGHT|wxALIGN_CENTER_VERTICAL|wxALL, 5 );

    wxTextCtrl *item42 = new wxTextCtrl( parent, ID_PLAYERAGILITY, wxT(""), wxDefaultPosition, wxSize(80,-1), 0 );
    item32->Add( item42, 0, wxALIGN_CENTER|wxALL, 5 );

    wxTextCtrl *item43 = new wxTextCtrl( parent, ID_PLAYERAGILITYF, wxT(""), wxDefaultPosition, wxSize(80,-1), wxTE_READONLY );
    item32->Add( item43, 0, wxALIGN_CENTER|wxALL, 5 );

    wxStaticText *item44 = new wxStaticText( parent, ID_TEXT, wxT("MaxHP"), wxDefaultPosition, wxDefaultSize, 0 );
    item32->Add( item44, 0, wxALIGN_RIGHT|wxALIGN_CENTER_VERTICAL|wxALL, 5 );

    wxTextCtrl *item45 = new wxTextCtrl( parent, ID_PLAYERMAXHP, wxT(""), wxDefaultPosition, wxSize(80,-1), 0 );
    item32->Add( item45, 0, wxALIGN_CENTER|wxALL, 5 );

    wxTextCtrl *item46 = new wxTextCtrl( parent, ID_PLAYERMAXHPF, wxT(""), wxDefaultPosition, wxSize(80,-1), wxTE_READONLY );
    item32->Add( item46, 0, wxALIGN_CENTER|wxALL, 5 );

    wxStaticText *item47 = new wxStaticText( parent, ID_TEXT, wxT("Accuracy"), wxDefaultPosition, wxDefaultSize, 0 );
    item32->Add( item47, 0, wxALIGN_RIGHT|wxALIGN_CENTER_VERTICAL|wxALL, 5 );

    wxTextCtrl *item48 = new wxTextCtrl( parent, ID_PLAYERACCURACY, wxT(""), wxDefaultPosition, wxSize(80,-1), 0 );
    item32->Add( item48, 0, wxALIGN_CENTER|wxALL, 5 );

    wxTextCtrl *item49 = new wxTextCtrl( parent, ID_PLAYERACCURACYF, wxT(""), wxDefaultPosition, wxSize(80,-1), wxTE_READONLY );
    item32->Add( item49, 0, wxALIGN_CENTER|wxALL, 5 );

    wxStaticText *item50 = new wxStaticText( parent, ID_TEXT, wxT("Dodging"), wxDefaultPosition, wxDefaultSize, 0 );
    item32->Add( item50, 0, wxALIGN_RIGHT|wxALIGN_CENTER_VERTICAL|wxALL, 5 );

    wxTextCtrl *item51 = new wxTextCtrl( parent, ID_PLAYERDODGING, wxT(""), wxDefaultPosition, wxSize(80,-1), 0 );
    item32->Add( item51, 0, wxALIGN_CENTER|wxALL, 5 );

    wxTextCtrl *item52 = new wxTextCtrl( parent, ID_PLAYERDODGINGF, wxT(""), wxDefaultPosition, wxSize(80,-1), wxTE_READONLY );
    item32->Add( item52, 0, wxALIGN_CENTER|wxALL, 5 );

    wxStaticText *item53 = new wxStaticText( parent, ID_TEXT, wxT("Strike Damage"), wxDefaultPosition, wxDefaultSize, 0 );
    item32->Add( item53, 0, wxALIGN_RIGHT|wxALIGN_CENTER_VERTICAL|wxALL, 5 );

    wxTextCtrl *item54 = new wxTextCtrl( parent, ID_PLAYERSTRIKEDAMAGE, wxT(""), wxDefaultPosition, wxSize(80,-1), 0 );
    item32->Add( item54, 0, wxALIGN_CENTER|wxALL, 5 );

    wxTextCtrl *item55 = new wxTextCtrl( parent, ID_PLAYERSTRIKEDAMAGEF, wxT(""), wxDefaultPosition, wxSize(80,-1), wxTE_READONLY );
    item32->Add( item55, 0, wxALIGN_CENTER|wxALL, 5 );

    wxStaticText *item56 = new wxStaticText( parent, ID_TEXT, wxT("Damage Absorb"), wxDefaultPosition, wxDefaultSize, 0 );
    item32->Add( item56, 0, wxALIGN_RIGHT|wxALIGN_CENTER_VERTICAL|wxALL, 5 );

    wxTextCtrl *item57 = new wxTextCtrl( parent, ID_PLAYERDAMAGEABSORB, wxT(""), wxDefaultPosition, wxSize(80,-1), 0 );
    item32->Add( item57, 0, wxALIGN_CENTER|wxALL, 5 );

    wxTextCtrl *item58 = new wxTextCtrl( parent, ID_PLAYERDAMAGEABSORBF, wxT(""), wxDefaultPosition, wxSize(80,-1), wxTE_READONLY );
    item32->Add( item58, 0, wxALIGN_CENTER|wxALL, 5 );

    wxStaticText *item59 = new wxStaticText( parent, ID_TEXT, wxT("HPRegen"), wxDefaultPosition, wxDefaultSize, 0 );
    item32->Add( item59, 0, wxALIGN_RIGHT|wxALIGN_CENTER_VERTICAL|wxALL, 5 );

    wxTextCtrl *item60 = new wxTextCtrl( parent, ID_PLAYERHPREGEN, wxT(""), wxDefaultPosition, wxSize(80,-1), 0 );
    item32->Add( item60, 0, wxALIGN_CENTER|wxALL, 5 );

    wxTextCtrl *item61 = new wxTextCtrl( parent, ID_PLAYERHPREGENF, wxT(""), wxDefaultPosition, wxSize(80,-1), wxTE_READONLY );
    item32->Add( item61, 0, wxALIGN_CENTER|wxALL, 5 );

    item30->Add( item32, 0, wxALIGN_CENTER|wxALL, 5 );

    item8->Add( item30, 0, wxALIGN_CENTER_HORIZONTAL|wxALL, 5 );

    wxStaticBox *item63 = new wxStaticBox( parent, -1, wxT("Inventory") );
    wxStaticBoxSizer *item62 = new wxStaticBoxSizer( item63, wxVERTICAL );

    wxBoxSizer *item64 = new wxBoxSizer( wxVERTICAL );

    wxFlexGridSizer *item65 = new wxFlexGridSizer( 3, 0, 0 );
    item65->AddGrowableCol( 2 );

    wxStaticText *item66 = new wxStaticText( parent, ID_TEXT, wxT("Slot"), wxDefaultPosition, wxDefaultSize, 0 );
    item65->Add( item66, 0, wxALIGN_CENTER|wxALL, 5 );

    wxSpinCtrl *item67 = new wxSpinCtrl( parent, ID_PLAYERINVENTORYSLOT, wxT("0"), wxDefaultPosition, wxSize(100,-1), wxSP_WRAP, 0, 15, 0 );
    item65->Add( item67, 0, wxALIGN_CENTER|wxALL, 5 );

    item65->Add( 20, 20, 0, wxALIGN_CENTER|wxALL, 5 );

    wxStaticText *item68 = new wxStaticText( parent, ID_TEXT, wxT("Item ID"), wxDefaultPosition, wxDefaultSize, 0 );
    item65->Add( item68, 0, wxALIGN_CENTER|wxALL, 5 );

    wxTextCtrl *item69 = new wxTextCtrl( parent, ID_PLAYERCURRENTITEMID, wxT(""), wxDefaultPosition, wxSize(100,-1), 0 );
    item65->Add( item69, 0, wxALIGN_CENTER|wxALL, 5 );

    wxTextCtrl *item70 = new wxTextCtrl( parent, ID_PLAYERCURRENTITEMNAME, wxT(""), wxDefaultPosition, wxSize(120,-1), wxTE_READONLY );
    item65->Add( item70, 0, wxALIGN_CENTER|wxALL, 5 );

    item64->Add( item65, 0, wxALIGN_CENTER|wxALL, 5 );

    wxStaticLine *item71 = new wxStaticLine( parent, ID_LINE, wxDefaultPosition, wxSize(200,-1), wxLI_HORIZONTAL );
    item64->Add( item71, 0, wxALIGN_CENTER|wxALL, 5 );

    wxFlexGridSizer *item72 = new wxFlexGridSizer( 3, 0, 0 );

    wxStaticText *item73 = new wxStaticText( parent, ID_TEXT, wxT("Weapon"), wxDefaultPosition, wxDefaultSize, 0 );
    item72->Add( item73, 0, wxALIGN_CENTER|wxALL, 5 );

    wxSpinCtrl *item74 = new wxSpinCtrl( parent, ID_PLAYERWEAPON, wxT("-1"), wxDefaultPosition, wxSize(100,-1), wxSP_WRAP, -1, 15, -1 );
    item72->Add( item74, 0, wxALIGN_CENTER|wxALL, 5 );

    wxTextCtrl *item75 = new wxTextCtrl( parent, ID_PLAYERWEAPONTEXT, wxT(""), wxDefaultPosition, wxSize(120,-1), wxTE_READONLY );
    item72->Add( item75, 0, wxALIGN_CENTER|wxALL, 5 );

    wxStaticText *item76 = new wxStaticText( parent, ID_TEXT, wxT("Armor"), wxDefaultPosition, wxDefaultSize, 0 );
    item72->Add( item76, 0, wxALIGN_CENTER|wxALL, 5 );

    wxSpinCtrl *item77 = new wxSpinCtrl( parent, ID_PLAYERARMOR, wxT("-1"), wxDefaultPosition, wxSize(100,-1), wxSP_WRAP, -1, 15, -1 );
    item72->Add( item77, 0, wxALIGN_CENTER|wxALL, 5 );

    wxTextCtrl *item78 = new wxTextCtrl( parent, ID_PLAYERARMORTEXT, wxT(""), wxDefaultPosition, wxSize(120,-1), wxTE_READONLY );
    item72->Add( item78, 0, wxALIGN_CENTER|wxALL, 5 );

    wxStaticText *item79 = new wxStaticText( parent, ID_TEXT, wxT("Money"), wxDefaultPosition, wxDefaultSize, 0 );
    item72->Add( item79, 0, wxALIGN_CENTER|wxALL, 5 );

    wxTextCtrl *item80 = new wxTextCtrl( parent, ID_PLAYERMONEY, wxT(""), wxDefaultPosition, wxSize(100,-1), 0 );
    item72->Add( item80, 0, wxALIGN_CENTER|wxALL, 5 );

    item64->Add( item72, 0, wxALIGN_CENTER|wxALL, 5 );

    item62->Add( item64, 0, wxALIGN_CENTER|wxALL, 5 );

    item8->Add( item62, 0, wxALIGN_CENTER_HORIZONTAL|wxALL, 5 );

    item0->Add( item8, 0, wxALIGN_CENTER|wxALL, 5 );

    if (set_sizer)
    {
        parent->SetAutoLayout( TRUE );
        parent->SetSizer( item0 );
        if (call_fit)
        {
            item0->Fit( parent );
            item0->SetSizeHints( parent );
        }
    }
    
    return item0;
}

// Implement menubar functions

wxMenuBar *MyMenuBarFunc()
{
    wxMenuBar *item0 = new wxMenuBar;
    
    wxMenu* item1 = new wxMenu;
    item1->Append( ID_LOAD, wxT("Load Files"), wxT("") );
    item1->Append( ID_SAVE, wxT("Save Files"), wxT("") );
    item1->AppendSeparator();
    item1->Append( ID_QUIT, wxT("Quit"), wxT("") );
    item0->Append( item1, wxT("File") );
    
    wxMenu* item2 = new wxMenu;
    item2->Append( ID_ITEMEDITOR, wxT("Item Editor"), wxT("") );
    item2->Append( ID_PLAYEREDITOR, wxT("Player Editor"), wxT("") );
    item0->Append( item2, wxT("Editors") );
    
    wxMenu* item3 = new wxMenu;
    item3->Append( ID_ABOUT, wxT("About"), wxT("") );
    item0->Append( item3, wxT("Help") );
    
    return item0;
}

// Implement toolbar functions

void MyToolBarFunc( wxToolBar *parent )
{
    parent->SetMargins( 2, 2 );
    
    
    parent->Realize();
}

// Implement bitmap functions


// End of generated file
