//------------------------------------------------------------------------------
// Header generated by wxDesigner from file: SimpleEdit.wdr
// Do not modify this file, all changes will be lost!
//------------------------------------------------------------------------------

#ifndef __WDR_SimpleEdit_H__
#define __WDR_SimpleEdit_H__

#if defined(__GNUG__) && !defined(__APPLE__)
    #pragma interface "SimpleEdit_wdr.h"
#endif

// Include wxWindows' headers

#ifndef WX_PRECOMP
    #include <wx/wx.h>
#endif

#include <wx/image.h>
#include <wx/statline.h>
#include <wx/spinbutt.h>
#include <wx/spinctrl.h>
#include <wx/splitter.h>
#include <wx/listctrl.h>
#include <wx/treectrl.h>
#include <wx/notebook.h>
#include <wx/grid.h>

// Declare window functions

#define ID_TEXT 10000
#define ID_ITEMID 10001
#define ID_ITEMNEW 10002
#define ID_ITEMSAVE 10003
#define ID_ITEMDELETE 10004
#define ID_ITEMNAME 10005
#define ID_ITEMTYPE 10006
#define ID_ITEMMIN 10007
#define ID_ITEMMAX 10008
#define ID_ITEMSPEED 10009
#define ID_ITEMPRICE 10010
#define ID_ITEMSTRENGTH 10011
#define ID_ITEMHEALTH 10012
#define ID_ITEMAGILITY 10013
#define ID_ITEMMAXHP 10014
#define ID_ITEMACCURACY 10015
#define ID_ITEMDODGING 10016
#define ID_ITEMSTRIKEDAMAGE 10017
#define ID_ITEMDAMAGEABSORB 10018
#define ID_ITEMHPREGEN 10019
wxSizer *ItemEdit( wxWindow *parent, bool call_fit = TRUE, bool set_sizer = TRUE );

#define ID_PLAYERID 10020
#define ID_PLAYERNEW 10021
#define ID_PLAYERSAVE 10022
#define ID_PLAYERDELETE 10023
#define ID_PLAYERNAME 10024
#define ID_PLAYERPASS 10025
#define ID_PLAYERRANK 10026
#define ID_PLAYERSTATPOINTS 10027
#define ID_PLAYEREXPERIENCE 10028
#define ID_PLAYERLEVEL 10029
#define ID_PLAYERROOM 10030
#define ID_PLAYERHP 10031
#define ID_PLAYERATTACKTIME 10032
#define ID_PLAYERSTRENGTH 10033
#define ID_PLAYERSTRENGTHF 10034
#define ID_PLAYERHEALTH 10035
#define ID_PLAYERHEALTHF 10036
#define ID_PLAYERAGILITY 10037
#define ID_PLAYERAGILITYF 10038
#define ID_PLAYERMAXHP 10039
#define ID_PLAYERMAXHPF 10040
#define ID_PLAYERACCURACY 10041
#define ID_PLAYERACCURACYF 10042
#define ID_PLAYERDODGING 10043
#define ID_PLAYERDODGINGF 10044
#define ID_PLAYERSTRIKEDAMAGE 10045
#define ID_PLAYERSTRIKEDAMAGEF 10046
#define ID_PLAYERDAMAGEABSORB 10047
#define ID_PLAYERDAMAGEABSORBF 10048
#define ID_PLAYERHPREGEN 10049
#define ID_PLAYERHPREGENF 10050
#define ID_PLAYERINVENTORYSLOT 10051
#define ID_PLAYERCURRENTITEMID 10052
#define ID_PLAYERCURRENTITEMNAME 10053
#define ID_LINE 10054
#define ID_PLAYERWEAPON 10055
#define ID_PLAYERWEAPONTEXT 10056
#define ID_PLAYERARMOR 10057
#define ID_PLAYERARMORTEXT 10058
#define ID_PLAYERMONEY 10059
wxSizer *PlayerEdit( wxWindow *parent, bool call_fit = TRUE, bool set_sizer = TRUE );

// Declare menubar functions

#define ID_MENU 10060
#define ID_LOAD 10061
#define ID_SAVE 10062
#define ID_QUIT 10063
#define ID_EDITORS 10064
#define ID_ITEMEDITOR 10065
#define ID_PLAYEREDITOR 10066
#define ID_HELP 10067
#define ID_ABOUT 10068
wxMenuBar *MyMenuBarFunc();

// Declare toolbar functions

void MyToolBarFunc( wxToolBar *parent );

// Declare bitmap functions

#endif

// End of generated file
